#!/usr/bin/env bash
#
# NETRA benchmark harness.
#
# Every number this produces is measured on the machine it runs on. Nothing
# here is a target, a projection, or a figure carried over from a previous run.
# Results vary with hardware, so the report records what it ran on.
#
#   NETRA_BENCH_URL=http://localhost:8095 ./bench/run.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE="${NETRA_BENCH_URL:-http://localhost:8095}"
OUT="${NETRA_BENCH_OUT:-${ROOT}/bench/results.md}"
SAMPLES="${NETRA_BENCH_SAMPLES:-200}"

command -v curl >/dev/null || { echo "curl is required" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }

if ! curl -sf "${BASE}/api/v1/health" >/dev/null; then
  echo "the backend is not reachable at ${BASE}" >&2
  exit 1
fi

token() {
  curl -s -X POST "${BASE}/api/v1/dev/token" \
    -H 'Content-Type: application/json' \
    -d "{\"subject\":\"bench\",\"roles\":[\"$1\"]}" |
    python3 -c 'import sys,json;print(json.load(sys.stdin)["access_token"])'
}

ANALYST="$(token SECURITY_ANALYST)"

# Measures wall-clock latency for one endpoint across SAMPLES requests and
# reports the distribution rather than an average, because an average hides the
# tail that an operator actually notices.
measure() {
  local label="$1" path="$2"
  local times=()
  for _ in $(seq 1 "$SAMPLES"); do
    times+=("$(curl -s -o /dev/null -w '%{time_total}' \
      -H "Authorization: Bearer ${ANALYST}" "${BASE}${path}")")
  done
  printf '%s\n' "${times[@]}" | python3 -c "
import sys
values = sorted(float(line) * 1000 for line in sys.stdin if line.strip())
def pct(p):
    return values[min(len(values) - 1, int(len(values) * p))]
print(f'| \`${label}\` | {len(values)} | {pct(0.5):.2f} | {pct(0.95):.2f} | {pct(0.99):.2f} | {values[-1]:.2f} |')
"
}

echo "measuring API latency over ${SAMPLES} samples per endpoint…" >&2

{
  echo "# NETRA benchmark results"
  echo
  echo "Generated by \`bench/run.sh\` on $(date -u '+%Y-%m-%d %H:%M:%SZ')."
  echo "Every figure is measured. None is a target or a projection."
  echo
  echo "## Environment"
  echo
  echo "| | |"
  echo "|---|---|"
  echo "| Host | $(uname -s) $(uname -r) $(uname -m) |"
  echo "| CPU cores | $(python3 -c 'import os;print(os.cpu_count())') |"
  echo "| Go | $(go version 2>/dev/null | awk '{print $3}' || echo 'not on PATH') |"
  echo "| Backend | ${BASE} |"
  echo "| Samples per endpoint | ${SAMPLES} |"
  echo
  echo "## API latency, milliseconds"
  echo
  echo "Wall clock from the client, so it includes connection setup, the"
  echo "database round trip and JSON encoding — not just handler time."
  echo
  echo "| Endpoint | Samples | p50 | p95 | p99 | max |"
  echo "|---|---:|---:|---:|---:|---:|"
  measure "GET /health" "/api/v1/health"
  measure "GET /overview" "/api/v1/overview"
  measure "GET /devices" "/api/v1/devices"
  measure "GET /sessions" "/api/v1/sessions"
  measure "GET /events?limit=100" "/api/v1/events?limit=100"
  measure "GET /incidents" "/api/v1/incidents"
  measure "GET /audit?limit=200" "/api/v1/audit?limit=200"
  echo
  echo "## Engine cost"
  echo
  echo "Go benchmarks for the components that sit in the access decision path."
  echo
  echo '```'
  (cd "${ROOT}/backend" && go test ./internal/risk/ ./internal/policy/ ./internal/posture/ \
     -run XXX -bench . -benchtime=100000x 2>/dev/null | grep -E '^Benchmark') || true
  echo '```'
  echo
  echo "## Endpoint agent footprint"
  echo
  if pgrep -f 'netra-agent' >/dev/null 2>&1; then
    echo "| | |"
    echo "|---|---|"
    ps -o rss=,%cpu= -p "$(pgrep -f 'netra-agent' | head -1)" |
      awk '{printf "| Resident memory | %.1f MB |\n| CPU | %s%% |\n", $1/1024, $2}'
  else
    echo "The agent was not running when this report was generated, so no"
    echo "footprint was measured. Start it and re-run rather than estimating."
  fi
  echo
  echo "## What is not measured yet"
  echo
  echo "- Ingest throughput at fleet scale. The simulator drives one endpoint at"
  echo "  a time; a multi-endpoint load generator is needed for a defensible"
  echo "  events-per-second figure."
  echo "- Detection precision and recall. These require a labelled corpus of"
  echo "  benign and malicious sessions, which does not exist yet. Quoting"
  echo "  either number from the current scenario set would be meaningless."
} > "${OUT}"

echo "wrote ${OUT}" >&2
